### ISSUE TITLE
xc3_tex xc2/menu/image/mnu032_button_push_main.wilay fails to rebuild properly

### ISSUE THREAD

**Issue by KenNZ23** [ScanMountGoat/xc3_lib#11]
Some wilay files contain multiple images (eg. mnu032_button_push_main.wilay). When these files are re-compiled some of the images contained within the wilay appear offset when displayed onscreen, while others may be offset outside the visible screen.

Here are the contents of the mnu032_button_push_main.wilay when extracted:
![push_button_map](https://github.com/ScanMountGoat/xc3_lib/assets/154410643/7c4c8ed7-113a-4322-8df0-7d498f39ee15)
The first image is the background, the second is a glow around the background, followed by pairs of buttons for swapping between the non-depressed and depressed states.

The original file should show these all layered on top of each other as below (ie. background, ring around border, 5th image [non-depressed B]):
![xc2-button-no_shift](https://github.com/ScanMountGoat/xc3_lib/assets/154410643/69b404d2-529d-4f18-9bb0-57825a8191a5)

The re-compiled file shows the first image in the correct position (the background) but is then failing to show the ring around border on-screen (it may be offset somewhere outside the visible screen?) then shows the fourth image (depressed button A) offset from the first. It also appears to fail to toggle between depressed and non-depressed states - possibly because the actual button that should be shown on screen are the 'B' pair which may be offset somewhere else...
![xc2-button-shift](https://github.com/ScanMountGoat/xc3_lib/assets/154410643/d4c77e1d-d55a-44bc-936f-531fddf1a723)

I can confirm that this still happens even when I do not edit or reorder any of the images, but simply extract, then immediately recompile the wilay without any change.

**Comment by ScanMountGoat** [comment]
There are 384 remaining wilay files that don't rebuild 1:1 for Xenoblade 2. Not all the files in this list will be broken, but all the broken files are likely to be in this list. mnu032_button_push_main.wilay is one of the files that doesn't rebuild properly yet due to some missing data. The goal is to try and get all the wilay rebuilding issues fixed for the next 0.5.0 release.

**Comment by ScanMountGoat** [comment]
The files aren't completely 1:1 yet, but this specific issue is fixed on the latest commit.

**Comment by KenNZ23** [comment]
I've tested this example in game by simply swapping the extracted dds files around (eg. replace A with B by simple renaming) and recompiling. The result appeared to work as expected. Thanks.
