### ISSUE TITLE
xc3_tex Texture Replacements with v2.2.0 Leisure Time models fail to build correctly  

### ISSUE THREAD

**Issue by tomasadam3** [ScanMountGoat/xc3_lib#12]
Not sure if it's because xc3_lib hasn't been updated since v2.2.0 dropped, but I've been unable to properly replace the textures of the Leisure Time models (tested only with Mio and Sena's so far). Loading the edited models in-game via Layered FS causes the game to freeze, and Noesis gives the following error when it tries to preview them (though xc3_viewer seems to have no problems reading/previewing them).
![error](https://github.com/ScanMountGoat/xc3_lib/assets/42417617/3baad393-0fab-46c9-b03c-d07bd9dcf27d)

**Comment by ScanMountGoat** [comment]
Thanks. I'll look into this for the next release.

**Comment by tomasadam3** [comment]
Thanks!

**Comment by ScanMountGoat** [comment]
Thank you for reporting this. There were two separate issues with that file. The data offsets weren't being set correctly, causing the noesis plugin to not load it. Some texture data related to the `chr/tex/nx` folder was also not being set properly, causing crashes in game. Both of these issues are fixed on the latest commit. You can compile from source or wait for the 0.5.0 release.
