### ISSUE TITLE
xeno1/chr/np/np860109.wimdo freezes in game after editing with xc3_tex

### ISSUE THREAD

**Issue by tomasadam3** [ScanMountGoat/xc3_lib#18]
Not sure if this is an issue specific to XCDE Alvis' model (np860109), or if it extends to other NPC models as well, but editing any of Alvis' textures appears to cause the game to freeze upon the edited model's load. The .wimdo and .wismt don't appear corrupted, as they load just fine in Noesis, but I still assume something went wrong. Below is the main texture I'm trying to edit in:

np860109.16.NP860101_NEC_COL
![image](https://github.com/ScanMountGoat/xc3_lib/assets/42417617/5956790a-4c44-4d80-abf1-bfcddaab6b42)

**Comment by ScanMountGoat** [comment]
Do you still get a crash if you don't edit any of the textures? There may be an issue with rebuilding either the wimdo or wismt file.

**Comment by tomasadam3** [comment]
Tested that just now and yea it does seem to be a rebuilding problem (same type of crash happens as soon as the model loads in).

**Comment by ScanMountGoat** [comment]
This may be fixed on the latest 0.9.0 release @tomasadam3. I don't have a way to test DE files in game at the moment. https://github.com/ScanMountGoat/xc3_lib/releases/tag/v0.9.0

**Comment by tomasadam3** [comment]
Thanks for the update. Unfortunately, the game still freezes as soon as the edited model gets loaded in.

**Comment by ScanMountGoat** [comment]
Thanks for getting back to me. That should help narrow it down as I keep looking into fixing this.

**Comment by ScanMountGoat** [comment]
This may be fixed on the latest commit. I've fixed some errors rebuilding fur rendering data that impacted that file. It would be great if you could test this build when you get a chance. You can also download and compile the code yourself if you have Rust installed. @tomasadam3 
[xc3_tex.zip](https://github.com/user-attachments/files/17152194/xc3_tex.zip)

**Comment by tomasadam3** [comment]
Alvis' model no longer crashes the game after editing it with xc3_tex, thanks for the fix!

On a related note, I noticed that xc3_tex now requires you to have all textures present in the image folder when performing texture replacements (not doing so will give errors such as "Found image index 16 but expected 0"). Was this change added recently?

**Comment by ScanMountGoat** [comment]
It's nice to see this finally fixed.

> Was this change added recently?

The replacement behavior was changed in one of the recent releases. xc3_tex expects all the textures to be present to be able to support adding or removing textures.
