### ISSUE TITLE
xeno1/chr/pc/pc0101305.wimdo glTF crashes in UE5

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xc3_lib#20]
Tested generated gltf files with [https://github.khronos.org/glTF-Validator/](url) & they come back with a bunch of errors.
Am trying to debug why specific files, DE's pc010305 for example, seem to crash the Unreal 5 editor (something about `EXCEPTION_ACCESS_VIOLATION reading address 0x00000001ffffffff`), while other files don't have that issue.

**Comment by ScanMountGoat** [comment]
Does the gltf file work in Blender? Not all validation errors are critical errors. Not including the min/max for position attributes is a validation error, for example. I'll try and export that specific file and see what may be causing compatibility issues.

**Comment by ScanMountGoat** [comment]
This should be fixed now if you build the latest commit from source with `cargo build --release`. The crashing is fixed for me with Unreal Engine 5.2.1.

**Comment by nanogram** [comment]
Not sure if this is part of this or just an unreal importer issue, but I've also noticed that model normals/smoothing groups don't seem to import properly. This is noticable on shirtless models like pc010102 iirc.

**Comment by ScanMountGoat** [comment]
There may be something you need to enable in the import settings in Unreal Engine. I would also check if this happens on glTF sample models. If you think the problem is xc3_gltf related, please open another issue.
