### ISSUE TITLE
DE Broken menu textures

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xc3_lib#21]
Tested on v0.7.0

img0103_1.0, img0103_2.0, img0103_3.0
![img0103_1 0](https://github.com/ScanMountGoat/xc3_lib/assets/14881073/750e5fa8-7425-4634-8316-bd22ac25f48d)

mf03_map01_ma2401_f01_map.0
![mf03_map01_ma2401_f01_map 0](https://github.com/ScanMountGoat/xc3_lib/assets/14881073/d8aac0cf-aec6-4b21-b8bd-b7e612362518)

npg_photo14.0
![npg_photo14 0](https://github.com/ScanMountGoat/xc3_lib/assets/14881073/634e60d4-91fd-4422-8d8c-7073691f00a7)

**Comment by ScanMountGoat** [comment]
I know I've tested the texture from img0103_1.wilay in Xenoblade 3 in Ryujinx and it still looked liked that. You can try swapping the textures from those onto an existing wilay and test in Xenoblade 1 in an emulator and see if you get anything different. Xenoblade 3 also has some textures that appear to be corrupted in some way like ma11a_01_s3_map.wilay.
