### ISSUE TITLE
Broken UVs for xeno1/chr/pc/pc082505.wimdo

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xc3_lib#26]
![image](https://github.com/ScanMountGoat/xc3_lib/assets/14881073/bea12eb2-18b0-4bee-965c-a1bc50d1e68f)

Tested on v0.8.0

**Comment by ScanMountGoat** [comment]
I'm only seeing one texcoord attribute. I'll investigate the shaders later to see if this is related to texture scaling parameters.

**Comment by ScanMountGoat** [comment]
The UV attributes in the decompiled shaders are just passed from vertex to fragment without any scaling or offsets. The vertex attribute data also appears normal. Is pc082505 a duplicate of pc080405?

**Comment by nanogram** [comment]
Yup. Scanned thru the pc080405 duplicates, and verified that none of them are used. They look to be wii filler weapons after checking tri count.
