### ISSUE TITLE
glTF model exports don't work in latest Unreal Editor

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xc3_lib#46]
Regression from v9.0 to v10.0
Starting from v10, using xc3_gltf to process xcde wimdo files with skeletons results in it being always detected as a static mesh when importing to UE5.
I ran into this issue when using the most current build, and the issue seems to have first popped up in v10.
Using v9 imports without issue.
`LogStaticMeshOperations: Display: Mesh 0 has NaNs in it's vertex instance tangent space! Offending tangents are set to zero.`

```LogInterchangeEngine: [Pending] Importing
LogStaticMeshOperations: Display: Mesh 0 has NaNs in it's vertex instance tangent space! Offending tangents are set to zero.
LogStaticMesh: Display: Building static mesh wp1101 (Required Memory Estimate: 3.816276 MB)...
LogStaticMesh: Built static mesh [0.04s] /Game/UNREAL_ENGINE_5/chr/wp/wp1101/wp1101.wp1101
LogStaticMesh: Warning: wp1101 has some nearly zero tangents which can create some issues. (Tolerance of 1E-4)
LogStaticMesh: Warning: wp1101 has some nearly zero bi-normals which can create some issues. (Tolerance of 1E-4)
LogInterchangeEngine: Display: Interchange import completed [D:/GameDevelopment/X...chr_MASTER/wp/wp1101/wp1101.gltf]
Interchange: Warning: [...p1101/wp1101.gltf : '', Unknown] Renamed Assets:
 OriginalName:[/Game/UNREAL_ENGINE_5/chr/wp/wp1101/wp1101_root0_r1_g0_350379_b0_257572] NewName:[/Game/UNREAL_ENGINE_5/chr/wp/wp1101/wp1101_root0_r1_g0_350379_b0_2575723]
 OriginalName:[/Game/UNREAL_ENGINE_5/chr/wp/wp1101/wp1101_root0_r6_1__g6_0__b0_488884] NewName:[/Game/UNREAL_ENGINE_5/chr/wp/wp1101/wp1101_root0_r6_1__g6_0__b0_4888841]
Interchange: Error: [...p1101/wp1101.gltf : '', Unknown] Invalid mesh data (NAN) was found and changed to zero. This may affect the mesh rendering.```

**Comment by ScanMountGoat** [comment]
What unreal editor version are you using?

**Comment by nanogram** [comment]
I am using v5.4 currently.
I had used v5.3 as well; I don't believe the gltf importer plugin changed much between versions.

**Comment by ScanMountGoat** [comment]
I'm seeing those assertions after upgrading from 5.2 to 5.4. The issue with NaN is fixed on the latest commit. The issue with skeletal meshes not importing appears to be affecting all imports. They work fine in Blender. I'll look into changing the node hierarchy for non map exports and see if that fixes it.

**Comment by nanogram** [comment]
Post-https://github.com/ScanMountGoat/xc3_lib/commit/6161744cddbec61e41886799d5bec0a268ece667, wp1105 now doesn't generate a static or skeletal mesh on UE5 import, only textures/materials. Looks to be the only DE weapon having this issue.

**Comment by ScanMountGoat** [comment]
I'm moving this to #47. UE5 doesn't seem to import skeletons with multiple root bones. There's some assertion error related to bones in the Unreal message log.
