### ISSUE TITLE
xc3_viewer: per-channel display hotkeys [enhancement]

### ISSUE THREAD

**Issue by Sir-Teatei-Moonlight** [ScanMountGoat/xc3_lib#50]
xc3_viewer currently allows for switching between output GBuffers with the number keys. It would be nice if the RGBA keys (and/or the XYZW keys) did similar by switching channels, allowing for more clear investigation of per-channel details without having to printscreen and paste into an image editor.

**Comment by ScanMountGoat** [comment]
I'll look into adding this for the next release. You can also use the texture viewer in RenderDoc to see the individual channels as a workaround for now.
