### ISSUE TITLE
export animations with xc3_gltf

### ISSUE THREAD

**Issue by ScanMountGoat** [ScanMountGoat/xc3_lib#52]
Users will need to specify the animation file(s) when exporting.
https://github.com/KhronosGroup/glTF-Tutorials/blob/main/gltfTutorial/gltfTutorial_006_SimpleAnimation.md

**Comment by nanogram** [comment]
Post 0.15.0 update errors when exporting animations; this seems to be a common error for many of the models. Looks to be triggered from identical animations with root bone names often mismatching model root bone names.
Animations still export correctly, 

**Example:**
**Syntax Params:**
`xc3_gltf "D:\path2model\en120501.wimdo" D:\path2output\en120501.glb --database xc1.bin --anim "D:\path2anim\me120501.mot"`

**Resulting Error:**
`ERROR [xc3_model::animation] No matching bone for Name("en120100_top")`

**Comment by ScanMountGoat** [comment]
The log messages won't impact the exporting. I wouldn't worry about missing bone messages unless the actual exported animation is broken.
